### PR TITLE
Migrated to Swift 4.2 (using autofix)

### PR DESCRIPTION
**Pull request by Anarchoschnitzel**
- also Migrated Example Project to Swift 4.2 (using autofix)
- addressed XCode 10 build error

### CODE REVIEW

**Comment by LcTwisk** [comment]
Hi man! Thanks for you contribution.
What's the advantage of setting the `alpha` instead of hiding the view?

**Comment by Anarchoschnitzel** [comment]
Oh adding these commits was an accident, as we used that stuff internally totally forgot that I merged that.
I only wanted to contribute the migration commit, sorry. How should I proceed, so only the Swift 4.2 Migration is getting merged?

**Comment by Anarchoschnitzel** [comment]
Yup, did that.
I also updated the .swift-version and the .travis.yml to use swift 4.2 / Xcode 10

**Comment by BloodyPixy** [comment]
When this will be applied?

**Comment by erikpoort** [comment]
@LcTwisk Could you update the version number in the pod spec?

**Pull request merged**
